### ISSUE TITLE
Lernraum generieren

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#101]
**User Story**

Als Lernender möchte ich einen Lernraum sehen, um eine realistische Empfindung der 3D Welt zu erhalten 

**Akzeptanzkriterien**

- [x] In der Babylon Szene wird eine Plane für den Boden generiert
- [x] Die Größe des Bodens ist variabel
- [x] Es gibt ein Babylon Material für den Boden mit Holz-Textur 
- [x] Die Größe des Raums muss variabel sein
- [x] Die Wände sollen angezeigt werden.
- [x] Es soll Innenwände geben (Siehe 0.1 Konzept)
- [x] Die Wände sollen eine Farbe haben.
- [x] Die Wände müssen passend modifiziert werden (Türöffnungen)

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Vorgehen der Generierung im Wiki dokumentiert
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] In Changelog aufgenommen (Wikiseite Adler Engine 0.0 Changelog)
- [x] Es gibt keine bekannten Bugs

**Comment by philgei** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/101?planning-poker) with ZenHub @AdLer-Lukas @DerKatsche @Lizardguard

**Comment by Lizardguard** [comment]
Changed from 8 story points to 13

**Comment by Lizardguard** [comment]
Doku im Wiki unter:
https://wiki.projekt-adler.eu/de/AdLerEngine/Entwicklung/Standartraumgeometrie
