### ISSUE TITLE
[Research] - Catch Block Implementierung

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#1016]
**Akzeptanzkriterien**

- [x] Informationen zur Implementierung gesammelt
- [x] Verbindung zu Logger abgeklärt
- [x] Ideale Nutzer Notifications von Fehlern festgelegt (Wie werden Fehler intern richtig weitergeleitet an Notification Manager oder whatever)
- [x] Researchergebnisse im Wiki dokumentiert
- [x] Wiki Link im Task als Kommentar hinzugefügt

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Ergebnisse der Recherche wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [x] Dokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [x] Research wurde, falls möglich, in UML Klassendiagrammen bzw. Komponentendiagrammen getestet
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by Lizardguard** [comment]
Zu Try Catch:
http://www.javascriptkit.com/javatutors/trycatch2.shtml

**Comment by Lizardguard** [comment]
https://wiki.projekt-adler.eu/de/AdLerEngine/Entwicklung/Fehlerhandling
