### ISSUE TITLE
[Research] - zu Shape Keys / Morph Targets in Babylon

### ISSUE THREAD

**Issue by Grunick** [ProjektAdLer/2D_3D_AdLer#1023]
**Problemstellung**

Da es uns möglich ist Shape Keys des Körper Meshes in das exportierte GLB zu packen, sollten wir überprüfen wie wir diese Shape Keys in Babylon bzw im Code ansprechen können. Hierdurch könnten wir die Körperform des Charakters im Avatar-Editor anpassbar machen (Dicker-Dünner, Größer-Kleiner).

**Akzeptanzkriterien**

- [x] Überprüfung zu Shape Keys in Babylon abgeschlossen
- [x] Folgetask für die Implementierung erstellt

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Researchergebnisse sind als ZenHub Kommentar dokumentiert (Wiki / MuralBoard / etc.)
- [x] Die Realisierung wurde erfolgreich durch den Product Owner abgenommen
- [x] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/1023?planning-poker) with Zenhub @AdLer-Lukas @DerKatsche @Grunick @Lizardguard @mountler

**Comment by DerKatsche** [comment]
Babylon Doku zu Morph Targets:
https://doc.babylonjs.com/features/featuresDeepDive/mesh/morphTargets
TLDR:
- importierte glTF's die Morph Targets erhalten werden automatisch mit einem Manager geladen
- Einfluss der Morph Targets kann über den Manager direkt oder auch per Animationen geschehen
- evtl. Limitationen bei mehreren Morph Targets auf demselben Mesh ("_Please be aware that most of the browsers are limited to 16 attributes per mesh. Adding a single morph target to a mesh add up to 4 new attributes (position + normal + tangents + uvs). This could quickly go beyond the max attributes limitation._", siehe Limitations am Ende des Doku Artikels)

**Comment by DerKatsche** [comment]
Nach Tests:
- Morph Targets werden ohne Änderung des Ladeprozesses mit der glb geladen
- einfach ansteuerbar
- Name des Meshes auf dem die Morph Targets liegen sollte bekannt sein oder Name jedes Morph Targets muss pro Model eindeutig und bekannt sein (jeweils um die Morph Targets eindeutig ansteuern zu können)
- Hardware-/Browser-Limitationen (genannt in Babylon Doku) scheinen für unsere Anwendung irrelevant zu sein

**Comment by DerKatsche** [comment]
#1071 <- Folgetask
