### ISSUE TITLE
Türen in Wände integrieren

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#104]
**User Story**

Als Entwickler möchte ich Türen passend in Wände einsetzen sodass diese sinnvoll in der Szene dargestellt werden.

**Akzeptanzkriterien**

- [ ] ~~Es muss mindestens 2 Türen geben~~
- [x] Die Türen sollen eine Farbe haben.
- [x] Die Tür muss aus einem Rahmen und der Türe selber als seperate Meshes bestehen.
- [x] Die Tür hat einen Türknauf
- [x] Das Asset muss geladen werden
- [x] Die Tür lässt sich über Animation öffnen

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [x] Vorgehen der Generierung im Wiki dokumentiert
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] In Changelog aufgenommen (Wikiseite Adler Engine 0.0 Changelog)
- [x] Es gibt keine bekannten Bugs

**Comment by philgei** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/104?planning-poker) with ZenHub @AdLer-Lukas @DerKatsche @Lizardguard

**Comment by AdLer-Lukas** [comment]
Tür ist 1,50m breit und 2,28 hoch
Datei liegt auf dem NAS unter 23D Team / Art und auf GitHub unter Assets
