### ISSUE TITLE
[UI/UX] - Kamera drehbar machen

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#1046]
**User Story**

Nutzende möchten alle Elemente der 3D-Lernumgebung genauer anschauen können.

**Problemstellung**

Die gesperrte Kamera schränkt Nutzende ein.

**Lösungsansatz**

Die Kamera in eingeschränktem Maß drehbar machen. Die Drehung nur in horizontaler Richtung möglich machen. Vertikaldrehungen und Panning bleiben weiter gesperrt.

**Akzeptanzkriterien**

- [x] Drehbare Kamera in horizontaler Richtung implementiert sodass die Kamera nur bis zum geraden draufschauen auf die Wände gedreht werden kann
- [x] Kamerasteuerung Desktop über Drücken, Halten und Bewegen der Mittleren Maustaste implementieren
- [x] Kamerasteuerung für Touchpads optimieren (zusätzlicher Tastendruck auf Tastatur?)
- [x] Kamerasteuerung für Mobil funktionstüchtig implementiert

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler/Designer klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [ ] Requirements sind erstellt/angepasst und auf Writerside dokumentiert
- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Implementierung ist gepusht
- [ ] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [ ] Unittests sind erstellt
- [ ] Alle Tests müssen bestanden sein
- [ ] Benutzerdokumentation wurde angelegt oder angepasst (Writerside)
- [ ] Changelog des jeweiligen Release wurde aktualisiert
- [ ] Es gibt keine bekannten Bugs oder für Bug wurde Issue erstellt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [ ] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)
- [ ] [Optional] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/1046?planning-poker) with Zenhub @AdLer-Lukas @DerKatsche @Grunick @Lizardguard @mountler

**Comment by DerKatsche** [comment]
Rotation mit Q/E hinzugefügt
