### ISSUE TITLE
[Research] - Interessanteres Lernraum und -weltmenü

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#1047]
**Problemstellung**

Die Menüs für Lernwelt und Lernraum sind relativ dröge.

-> Vorherige Researchergebnisse: https://wiki.projekt-adler.eu/de/Didaktik/DTK-3D-AMG-Koop/8

**Akzeptanzkriterien**

- [ ] Erarbeiten, wie eine Raum Preview im Menü als Vorschau gezeigt werden könnte
- [ ] Research für Icons zur Veranschaulichung nutzen
- [ ] Möglichkeit einer stilisierten Karte à la Super Mario, Umsetzungsszenario recherchieren (nicht, ob das gut oder schlecht wäre, sondern wie könnten wir es einbauen)
- [ ] Task erstellen für Absprache mit DTK

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Researchergebnisse sind als ZenHub Kommentar dokumentiert (Wiki / MuralBoard / etc.)
- [ ] Die Realisierung wurde erfolgreich durch den Product Owner abgenommen
- [ ] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/1047?planning-poker) with Zenhub @AdLer-Lukas @DerKatsche @Grunick @Lizardguard @mountler

**Comment by Lizardguard** [comment]
Beispiele Graph ansicht lernraummenu:
![grafik](https://github.com/user-attachments/assets/f44bedcd-5dd3-49d3-ae41-8ab8e7c509ce)
![grafik](https://github.com/user-attachments/assets/032eeefa-9a1e-4108-967d-90c697d3fb53)
![grafik](https://github.com/user-attachments/assets/221430eb-ecf2-4488-ac10-ee2b5e6490bc)

**Comment by Lizardguard** [comment]
Beispiel Lernwelt menu:
![grafik](https://github.com/user-attachments/assets/3f796d6f-b76f-470b-b74a-884bdd770473)
