### ISSUE TITLE
[Research] - Overhead Namensschild Character & NPC

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#1048]
**Problemstellung**

Wiedererkennungswert der Character und NPCs erhöhen.

**Akzeptanzkriterien**

- [x] Sollten NPCs Namen bekommen
- [x] Wollen wir den Accountnamen beim Character anzeigen oder einen eigenen Namen vergeben lassen?
- [x] Mit Team Didaktik und Autorentool abstimmen
- [ ] Task zur Implementierung erstellt

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden Beteiligten klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Researchergebnisse sind als ZenHub Kommentar dokumentiert (Wiki / MuralBoard / etc.)
- [ ] Die Realisierung wurde erfolgreich durch den Product Owner abgenommen
- [ ] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/1048?planning-poker) with Zenhub @AdLer-Lukas @DerKatsche @Grunick @Lizardguard @mountler

**Comment by DerKatsche** [comment]
- Im Zuge der neuen Game-Based Learning Mechniken besprochen
- NPCs sollen Namen bekommen
- Namen sollen nicht im Raum, aber im die Dialogfenster
- Noch kein Implementierungstask geschrieben, da dies dann nach dem Avatar-Editor mit den anderen GBL-Tasks passiert
