### ISSUE TITLE
[Research] - H5Ps testen

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#1054]
**Problemstellung**

Wir wissen nicht, welche H5Ps in unserem aktuellen Setup funktionieren.

**Akzeptanzkriterien**

- [ ] ~~Liste mit vorhandenen H5Ps erstellt (aus MKD Kursen, Workshops, eigenen Kursen, etc.)?~~
- [x] Alle 73 H5Ps mit Lumi erstellen, so dass sie im Test einfach abgeschlossen werden können
- [x] Kurs auf Production mit den zu testenden H5Ps erstellt
- [x] H5Ps getestet und Funktion/Nicht Funktion dokumentiert
- [ ] Weiterführenden Task in Richtung Implementierung erstellt / bzw. bestehende Tasks angepasst

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Researchergebnisse sind als ZenHub Kommentar dokumentiert (Wiki / MuralBoard / etc.)
- [ ] Die Realisierung wurde erfolgreich durch den Product Owner abgenommen
- [ ] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/1054?planning-poker) with Zenhub @AdLer-Lukas @DerKatsche @Grunick @Lizardguard @mountler

**Comment by AdLer-Lukas** [comment]
Whitelist/Blacklist 
https://cloud.projekt-adler.eu/f/182283
