### ISSUE TITLE
[Research] - Content für Steuerungserklärung erstellen

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#1056]
**Problemstellung**

Modal braucht Content.

**Akzeptanzkriterien**

- [x] Modal konzeptioniert
- [x] Texte erstellt
- [x] Grafiken erstellt

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Researchergebnisse sind als ZenHub Kommentar dokumentiert (Wiki / MuralBoard / etc.)
- [ ] Die Realisierung wurde erfolgreich durch den Product Owner abgenommen
- [ ] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/1056?planning-poker) with Zenhub @AdLer-Lukas @DerKatsche @Grunick @Lizardguard @mountler

**Comment by AdLer-Lukas** [comment]
<img width="1382" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3lrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e11e5c99baf7032511cb65dca0bfb86d2d4577f0/Element%202-80.jpg" alt="Element 2-80.jpg" />

**Comment by AdLer-Lukas** [comment]
<img width="448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzJrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4fcab50f6cb2a29499ecc3a92382c2271fc7d652/Element%203-80.jpg" alt="Element 3-80.jpg" />
