### ISSUE TITLE
Als neuer Entwickler möchte ich einen Überblick zum Setup der Entwicklungsumgebung haben

### ISSUE THREAD

**Issue by DerKatsche** [ProjektAdLer/2D_3D_AdLer#106]
**User Story**

Als neuer Entwickler möchte ich einen Überblick zum Setup der Entwicklungsumgebung haben

**Akzeptanzkriterien**

- [x] Ein klarer Eintrag dazu findet sich im Wiki

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Benutzerdokumentation angelegt (Wiki)
- [x] Technische Dokumentation angelegt (ZenHub)

**Comment by Lizardguard** [comment]
https://wiki.projekt-adler.eu/de/AdLerEngine/Entwicklung/Adler_Engine_Tools_Setup
