### ISSUE TITLE
[UI/UX] - Ladebildschirm Lernwelten ohne Steuerungserklärung

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#1062]
**User Story**

Als Nutzer möchte ich einen kontextspezifischen Ladebildschirm für das Lernwelt- und das Lernraummenü haben

**Problemstellung**

In den Ladebilschirm wurde die Steuerungserklärung für die 3D-Szene eingebaut. 
Die Steuerungserklärung wird allerdings beim Laden des Lernweltmenüs auch angezeigt.

**Lösungsansatz**

Der Ladebilschirm wird so angepasst, dass er beim Laden der Lernwelten keine Steuerungserklärung anzeigt und trotzdem chic aussieht :) 

**Akzeptanzkriterien**

- [x] Ladebildschirm mit der Möglichkeit unterschiedlichen Content anzuzeigen implementiert
- [x] Möglichkeit den Button gegen eine automatische Weiterleitung zu ersetzen implementiert
- [x] Die Strings in den Buttons für die jeweilige Situation angepasst
- [x] Generischer Content für Lernraummenü/Lernweltmenü/Avatar Ladebildschirm erstellt
- [x] Ladebildschirm mit passendem Content zu Lernraummenü implementiert
- [x] Ladebildschirm mit passendem Content zu Lernweltmenü implementiert
- [x] Ladebildschirm mit passendem Content zu Avatar-Editor implementiert
- [x] Ladebildschirm mit passendem Content zu 3D-Lernumgebung (Steuerungserklärung) implementiert

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler/Designer klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [x] Requirements sind erstellt/angepasst und auf Writerside dokumentiert
- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist gepusht
- [x] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [x] Unittests sind erstellt
- [x] Alle Tests müssen bestanden sein
- [x] Benutzerdokumentation wurde angelegt oder angepasst (Writerside)
- [x] Changelog des jeweiligen Release wurde aktualisiert
- [x] Es gibt keine bekannten Bugs oder für Bug wurde Issue erstellt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)
- [x] [Optional] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert

**Comment by Lizardguard** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/1062?planning-poker) with Zenhub @splican
