### ISSUE TITLE
Navmesh für Nutzer-Bewegungsbereich im Lernraum generieren

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#107]
**User Story**

Als Nutzer möchte ich mich in einem festgelegten Bereich bewegen können, sodass ich keine Fehlbedienung begehen kann. 

**Akzeptanzkriterien**

- [ ] ~~Die Bewegungsfläche im Lernraum wird generisch anhand der DTO erzeugt~~
- [x] Die Bewegungsfläche begrenzt die Bewegungsfläche des Avatars sinnvoll 
- [x] Das Navmesh spart alle 3D Geometrien im Lernraum aus, sodass sich der Avatar in keine anderen 3D Modelle bewegen kann. 

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Benutzerdokumentation angelegt (Handbuch)
- [ ] Technische Dokumentation angelegt (ZenHub)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by DerKatsche** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/107?planning-poker) with ZenHub @Lizardguard @LuckyLuke28 @philgei @splican
