### ISSUE TITLE
[Bug] - NavMesh außerhalb des Raums generiert

### ISSUE THREAD

**Issue by DerKatsche** [ProjektAdLer/2D_3D_AdLer#1072]
**Beschreibung des Problems:**

Durch die Raumdeko wird manchmal Navmesh auf den flachen Flächen außerhalb des Raums generiert. Der Nutzende kann darauf klicken, der Bewegungsindikator wird auf dem Boden angezeigt und der Avatar versucht auch dorthin zu laufen. Die Bewegung wird dann aber abgebrochen wenn der Avatar gegen den Rand des Lernraums läuft. 
Kann außerdem zu Problemen mit dem Avatar-Spawn führen, da diese auch auf das NavMesh geclampt werden.

**Schritte zum Reproduzieren:**

(bitte möglichst _genaue_ Beschreibung, wie und unter welchen Umständen das Problem reproduziert werden kann und, falls nötig, relevante Dateien anhängen)

**Informationen zum Endgerät:**

(Bitte möglichst detaillierte Informationen zum Endgerät und Browser)

**Erwartetes Verhalten:**

Keine begehbaren Flächen (generiertes NavMesh) außerhalb des Raums

**Tatsächliches Verhalten:**

(ausführliche Beschreibung des Fehlerverhaltens, falls möglich. Gerne auch Screenshot, Log, etc.)

**Ansprechpartner:**

@DerKatsche 

**Akzeptanzkrieterien**

- [x] Für Deko im Raum und außerhalb jeweils eine GLB pro Theme/Template erstellen
- [x] Anpassung des Codes für Laden der Deko 

**Lösung (erst bei Fix angeben):**

Trennen von Lernraum-Deko in 2 Models: eins für alle Meshes außerhalb des Raums, eins für alle innerhalb

**Comment by Lizardguard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/1072?planning-poker) with Zenhub @AdLer-Lukas @DerKatsche @mountler @Grunick
