### ISSUE TITLE
[Bug] - Fehlermeldung für Nutzenden bei nicht anzeigbarem Video

### ISSUE THREAD

**Issue by DerKatsche** [ProjektAdLer/2D_3D_AdLer#1083]
**Beschreibung des Problems:**

Bei einem nicht anzeigbarem Video in einem Videolernelement (siehe Vorgänger-Bug #624) wird ein für den Nutzer nicht lesbarer Browserfehler angezeigt. 

**Schritte zum Reproduzieren:**

Anzeigen eines Video vom THAB Videoserver in einem Video-Lernelement, dass nicht öffentlich freigegeben ist

**Informationen zum Endgerät:**

(Bitte möglichst detaillierte Informationen zum Endgerät und Browser)

**Erwartetes Verhalten:**

Der Fehler sollte Nutzer-lesbar sein und darauf verweisen, dass der Prof/Tutor evtl. das Video freigeben kann.

**Tatsächliches Verhalten:**

(ausführliche Beschreibung des Fehlerverhaltens, falls möglich. Gerne auch Screenshot, Log, etc.)

**Ansprechpartner:**

(für weitere Fragen)

**Akzeptanzkriterien**

~~- [ ] Fehler abgefangen~~
~~- [ ] sinnvolle Fehlermeldung wird angezeigt~~

**Lösung (erst bei Fix angeben):**

(wird durch Team 3D ausgefüllt)

**Comment by splican** [comment]
Weitere Abstimmung mit Autorentool benötigt. Da es nach aktuellem Wissensstand nicht möglich ist, die nicht öffentlichen Videos anzuschauen.
Die Eingabe der Videos sollte validiert werden, bzw. dem Nutzenden eine Information angezeigt werden, dass bei Eingabe eines nicht öffentlichen Videos Probleme zu erwarten sind.
