### ISSUE TITLE
[Research] - Alternative für ELKjs

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#1085]
**Problemstellung**

Die Bibliothek ELKjs hat eine restriktive Lizenz die durch eine offenere Lizenz - min. Apache 2.0 - ersetzt werden soll. Um AdLer Engine auf Apache 2.0. zu lizenzieren 

**Akzeptanzkriterien**

- [x] Bibliotheken recherchieren 
- [x] Bibliotheken vergleichen 
- [x] Für Bibliothek entscheiden 
- [x] Bibliothek implementieren 
- [x] Breite der Nodes für Räume/Nicht-Räume anpassen 

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Researchergebnisse sind als ZenHub Kommentar dokumentiert (Wiki / MuralBoard / etc.)
- [x] Die Realisierung wurde erfolgreich durch den Product Owner abgenommen
- [x] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)

**Comment by DerKatsche** [comment]
Neue Layouting Bib dagrejs ist MIT Lizenz
