### ISSUE TITLE
[Bug] - Framerate Babylon.js reduzieren

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#1086]
**Beschreibung des Problems:**

(kurze Beschreibung des Fehlerverhaltens)

**Schritte zum Reproduzieren:**

(bitte möglichst _genaue_ Beschreibung, wie und unter welchen Umständen das Problem reproduziert werden kann und, falls nötig, relevante Dateien anhängen)

**Informationen zum Endgerät:**

(Bitte möglichst detaillierte Informationen zum Endgerät und Browser)

**Erwartetes Verhalten:**

(Erwartetes Verhalten nach eigenem Verständnis)

**Tatsächliches Verhalten:**

(ausführliche Beschreibung des Fehlerverhaltens, falls möglich. Gerne auch Screenshot, Log, etc.)

**Ansprechpartner:**

(für weitere Fragen)

**Akzeptanzkrieterien**

~~- [ ] 30 FPS (normale Geräte)~~
~~- [ ] Maximal 60 FPS (bei schnellen Geräten)~~
- [x] Research ist erfolgt - siehe Kommentar

**Lösung (erst bei Fix angeben):**

(wird durch Team 3D ausgefüllt)

**Comment by DerKatsche** [comment]
Nicht wirklich möglich, da Navigation scheinbar von einem laufenden render loop abhängig ist.
Siehe Bsp. für custom render loop, die FPS theoretisch fixen können:
https://www.html5gamedevs.com/topic/2287-limit-frames-per-second/

**Comment by DerKatsche** [comment]
Ggf. renderloop pausieren an relevanten Punkten und allgemein Performance verbessern
