### ISSUE TITLE
[Bug] - Textausrichtung Storyelement

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#1091]
**Beschreibung des Problems:**

Text im Storyelement ist standardmäßig zentriert. Wenn ein Text über mehrere Zeilen geht, rutscht der Text zu linksorientiert. 

**Schritte zum Reproduzieren:**

Adaptivitätselement mit längerem Text ansehen.

**Informationen zum Endgerät:**

WIN 11 Desktop WQHD Display, Firefox 100% Browserskalierung

**Erwartetes Verhalten:**

Kompletter Text ist einheitlich links oder zentriert

**Tatsächliches Verhalten:**

Texte sind unterschiedliech angeordnet

**Ansprechpartner:**

@splican 

**Akzeptanzkrieterien**

- [x] Textausrichtung wurde links oder zentriert festgelegt
- [x] Textausrichtung im Storyelement wurde gefixed

**Lösung (erst bei Fix angeben):**

(wird durch Team 3D ausgefüllt)

**Comment by AdLer-Lukas** [comment]
Text ist jetzt immer links ausgerichtet
