### ISSUE TITLE
[Research] - Avatar Modell an Anforderungen des Avatar-Creators anpassen

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#1099]
**Problemstellung**

Wie muss der Avatar als Modell aufgebaut sein, dass wir die Assets einfach wechseln können?

**Akzeptanzkriterien**

- [x] Ankerpunkte für konfigurierbare Avatarkomponenten festgelegt und dokumentiert
- [x] Interaktionen und Einflussnahme von Animationen auf Avatarkomponenten überprüft und dokumentiert
- [x] UV-Verschiebungen von Texturen zur genauen Auswahl standardisiert und dokumentiert
- [x] Einfluss von Materialänderungen überpüft

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Researchergebnisse sind als ZenHub Kommentar dokumentiert (Wiki / MuralBoard / etc.)
- [x] Die Realisierung wurde erfolgreich durch den Product Owner abgenommen
- [x] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)

**Comment by DerKatsche** [comment]
WIP Wiki Artikel: https://wiki.projekt-adler.eu/de/AdLerEngine/Entwicklung/AdLerEngine

**Comment by DerKatsche** [comment]
Fragen zu genauer Implementierung der Variablen Models am Avatar und folge auf Animation Weights wird von Hiwis untersucht
