### ISSUE TITLE
User Story Templates schreiben

### ISSUE THREAD

**Issue by DerKatsche** [ProjektAdLer/2D_3D_AdLer#110]
**User Story**

Es werden neue, granularere Templates für User Stories benötigt. 
Template Typen werden als einzelne Akzeptanzkriterien beschrieben.

**Akzeptanzkriterien**

- [x] Code User Story Template
- [x] Recherche User Story Template

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Es gibt keine bekannten Bugs

**Comment by Lizardguard** [comment]
Additionally to the requested coding and research templates i've added an asset template as well.

**Comment by Lizardguard** [comment]
Additionally created a template for prototyping.
