### ISSUE TITLE
Protoyp Szene auf Repo anlegen 

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#112]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] Es gibt eine Szene auf dem Repository um Prototypen umsetzen zu können 

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [ ] Benutzerdokumentation angelegt (Handbuch)
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Es gibt keine bekannten Bugs

**Comment by DerKatsche** [comment]
Die neue Szene liegt unter .\src\Babylon\Prototyping\PrototypeScene.ts und kann ganz normal bearbeitet werden.
Um die Szene in den lokalen Dev Server zu laden, muss **lokal** der Pfad der Methode getSceneModule() unten in der Datei .\src\Babylon\CreateScene.ts auf den Pfad der Prototypszene geändert werden.
Fragen einfach an mich auf Discord
