### ISSUE TITLE
Assets-Tabelle in Wiki und Anforderungen festlegen

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#114]
**User Story**

Für die Entwicklung der AdLer Engine ist es wichtig Konventionen für Assets festzulegen, sodass eine gute Performance sichergestellt ist. 

**Akzeptanzkriterien**

- [x] Einzelne Assetsklassen werden kategorisiert
- [x] Modelle passen in vorgesehene Bereiche auf Grundriss bzw. in Wandloch
- [x] Model Anforderungen aufgeführt (z.B. Maßstab, Origin, UV-Maps, initiale Rotation)
- [x] SVG-Vorgaben
- [x] Assetliste als Tabelle mit aktuellem Stand auf Wiki

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Ergebnisse der Recherche wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [ ] Dokumentation wurde, falls nötig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [ ] Research wurde, falls möglich, in UML Klassendiagrammen bzw. Komponentendiagrammen getestet
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by DerKatsche** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/114?planning-poker) with ZenHub @Lizardguard @LuckyLuke28 @philgei @splican

**Comment by splican** [comment]
Plugin für Blender, welches die Modelle anpasst?
