### ISSUE TITLE
H5P-Lernelement als 3D Modell darstellen

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#125]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] 3D Modell liegt als GLB Asset vor 
- [x] Das 3D Modell kann an geeigneter Stelle im 3D-Raum platziert werden

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist in GitHub
- [x] Die Codekonventionen sind eingehalten
- [x] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [x] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [ ] UML Klassendiagramme und Komponentendiagramme wurden erstellt bzw. aktualisiert
- [x] Changelog des jeweiligen Release wurde aktualisiert (Wiki)
- [x] Es gibt keine bekannten Bugs
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by DerKatsche** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/125?planning-poker) with ZenHub @AdLer-Lukas @Lizardguard
