### ISSUE TITLE
Akti Workshop

### ISSUE THREAD

**Issue by DerKatsche** [ProjektAdLer/2D_3D_AdLer#131]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] Termin festgelegt
- [x] Workshop durchgeführt
- [x] Ergebnisse im Wiki dokumentiert

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Ergebnisse der Recherche wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [x] Dokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [x] Research wurde, falls möglich, in UML Klassendiagrammen bzw. Komponentendiagrammen getestet
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by DerKatsche** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/131?planning-poker) with ZenHub @AdLer-Lukas @Lizardguard

**Comment by DerKatsche** [comment]
Termin: Montag 13:00 Uhr Akti Besprechung

**Comment by Lizardguard** [comment]
Momentan On Hold da das WIki zur Zeit nicht erreichbar ist.
