### ISSUE TITLE
Aktivitätsdiagramme nachtragen

### ISSUE THREAD

**Issue by Lizardguard** [ProjektAdLer/2D_3D_AdLer#134]
**Akzeptanzkriterien**

- [x] Alle Aktis die im Akti Workshop identifiziert wurden sind nachgetragen

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Aktis wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by DerKatsche** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/134?planning-poker) with ZenHub @AdLer-Lukas @Lizardguard

**Comment by Lizardguard** [comment]
Ein Akti für alles mit unterschiedlichen Detailgraden.
Übergeordnetes Akti: Initialisierung, Gameloop, Aufräumen
Swimlanes vertikal
Lieber weniger als mehr uml (Vorgabe 7+-2)
Fehlerfälle beachten und suchen!
