### ISSUE TITLE
Anzeigekomponente für Video Lernelemente erstellen

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/2D_3D_AdLer#145]
**User Story**

Als Nutzer möchte ich Videos als 2D Lernelemente ansehen 

**Akzeptanzkriterien**

- [x] Das 2D Lernelement öffnet sich im auf dem Nutzerbildschirm 
- [x] Das 2D Lernelement kann wieder geschlossen werden 

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist in GitHub
- [x] Die Codekonventionen sind eingehalten
- [x] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [x] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [x] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [ ] UML Klassendiagramme und Komponentendiagramme wurden erstellt bzw. aktualisiert
- [x] Changelog des jeweiligen Release wurde aktualisiert (Wiki)
- [x] Es gibt keine bekannten Bugs
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by Lizardguard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/145?planning-poker) with ZenHub @AdLer-Lukas @DerKatsche @philgei

**Comment by DerKatsche** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/145?planning-poker) with ZenHub @splican
