### ISSUE TITLE
React Komponenten Anbindung

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#158]
**User Story**

React Komponenten müssen an dieselben Presenter und View Models angebunden werden wie ihr Babylon Gegenstück.
Dazu müssten die React Komponenten mit ihrem Presenter verbunden werden, dies gilt es auf eine architektonisch gute Weise zu recherchieren und zu implementieren. 

**Akzeptanzkriterien**

- [x] Wurde von Tobi und Georg abgesegnet
- [x] Presenter nimmt User Interaktionen von React entgegen und entscheidet wie sie verarbeitet werden 
- [x] Presenter bietet Zugriff auf das View Model für React 
- [x] Im View Model liegen alle für die Anzeige relevanten Daten 
- [x] Presenter kann zur Laufzeit zugewiesen werden

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist in GitHub
- [x] Die Codekonventionen sind eingehalten
- [x] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [x] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [ ] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert falls nötig
- [x] Changelog des jeweiligen Release wurde aktualisiert (Wiki)
- [x] Es gibt keine bekannten Bugs
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by Lizardguard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/158?planning-poker) with ZenHub @AdLer-Lukas @DerKatsche @philgei @splican
