### ISSUE TITLE
Team Didaktik zur motivationsfördernden Gestaltung von Lernwelten befragen

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#175]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] Meeting mit Team Didaktik zur Kooperation bei Designfragen durchführen 
- [x] Vereinbarungen zur Kooperation in einem Dokument festhalten und kommunizieren
- [x] Workshop für Verbundtreffen vorbereitet

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Benutzerdokumentation angelegt (Handbuch)
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [x] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by DerKatsche** [comment]
bei Paula angemeldet
