### ISSUE TITLE
Release Planning 0.2

### ISSUE THREAD

**Issue by LuckyLuke28** [ProjektAdLer/2D_3D_AdLer#182]
**User Story**

Als 3D Team möchten wir ein gemeinsames Release Planning 0.2 mit allen Projektbeteiligten durchführen, um alle Anforderungen der Stakeholder priorisiert in die Entwicklung einfließen zu lassen. 

**Akzeptanzkriterien**

- [x] Vom 3D Team geplante Features für 0.2 werden vorab auf dem Mural Board dokumentiert 
- [x] Es wird ein Termin mit allen Projektbeteiligten abgestimmt 
- [x] Das Release Planning 0.2 wird durchgeführt 
- [x] Die Features für AdLer Engine 0.2 sind eindeutig dokumentiert und priorisiert

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Benutzerdokumentation angelegt (Handbuch)
- [x] Technische Dokumentation angelegt (ZenHub)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by DerKatsche** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/182?planning-poker) with ZenHub @Lizardguard @LuckyLuke28 @philgei @splican
