### ISSUE TITLE
Modal Darstellung von AdLer Engine 0.1 optimieren

### ISSUE THREAD

**Issue by LuckyLuke28** [ProjektAdLer/2D_3D_AdLer#183]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] Modal Höhe ist maximal auf 100 % (kein Scrolling erforderlich)
- [x] Modal passt sich an den Inhalt an (Höhe+Breite)
- [x] Schliessen Button ist rechts oben, unabhängig ob Titel vorhanden ist oder nicht
- [x]  Bild wird richtig angezeigt (kleine und große Anzeige)
- [x]  Text wird richtig angezeigt (kleine und große Anzeige)
- [x]  Video wird richtig angezeigt (kleine und große Anzeige)
- [x] H5P wird richtig angezeigt (kleine und große Anzeige)

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Benutzerdokumentation angelegt (Handbuch)
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [x] Es gibt keine bekannten Bugs

**Comment by DerKatsche** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/183?planning-poker) with ZenHub @Lizardguard @LuckyLuke28 @philgei @splican
