### ISSUE TITLE
Fixing der Tests

### ISSUE THREAD

**Issue by Lizardguard** [ProjektAdLer/2D_3D_AdLer#184]
**User Story**

Zwei Unitstests schlagen mit folgendem Fehler fehl:

```
    TypeError: Cannot read properties of undefined (reading 'name')

      59 |     }
      60 |
    > 61 |     this.presenter = CoreDIContainer.get<ILearningRoomPort>(
         |                                      ^
      62 |       PORT_TYPES.ILearningRoomPort
      63 |     );
      64 |     (this.presenter as LearningRoomPresenter).ViewModel = this.viewModel;
```

**Akzeptanzkriterien**

- [x] Alle Tests laufen erfolgreich durch.

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Implementierung ist in GitHub
- [ ] Die Codekonventionen sind eingehalten
- [ ] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [ ] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [ ] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert falls nötig
- [ ] Changelog des jeweiligen Release wurde aktualisiert, falls erforderlich (Wiki)
- [ ] Es gibt keine bekannten Bugs
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by DerKatsche** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/184?planning-poker) with ZenHub @Lizardguard @LuckyLuke28 @philgei @splican

**Comment by DerKatsche** [comment]
Problem entsteht immer dann wenn im Produktionscode per DI eine Klasse instanziiert wird nachdem im Testcode per Jest eine deren Methoden gemockt wurde
-> Lösung unwahrscheinlich, Workaround notwendig

**Comment by DerKatsche** [comment]
adjusted estimate from 8 to 5
