### ISSUE TITLE
Browserleiste auf Mobilgeräten ausblenden (read Comment)

### ISSUE THREAD

**Issue by LuckyLuke28** [ProjektAdLer/2D_3D_AdLer#185]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] AdLer Engine wird Fullscreen auf Mobilgeräten angezeigt 
- [x] Darstellung nur im Landscape-Modus ermöglichen

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist in GitHub
- [x] Die Codekonventionen sind eingehalten
- [ ] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [ ] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [x] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [x] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert falls nötig
- [x] Changelog des jeweiligen Release wurde aktualisiert, falls erforderlich (Wiki)
- [x] Es gibt keine bekannten Bugs
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by Lizardguard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/185?planning-poker) with ZenHub @DerKatsche @philgei @splican @LuckyLuke28

**Comment by Lizardguard** [comment]
https://www.w3schools.com/jsref/met_element_requestfullscreen.asp

**Comment by philgei** [comment]
Fullscreen ist auf allen Desktop Geräten möglich. Auch auf Ipad und Android Tablets. **Auf Iphone allerdings nicht.**
