### ISSUE TITLE
(Recherche) Texturen in Babylon dynamisch ändern

### ISSUE THREAD

**Issue by LuckyLuke28** [ProjektAdLer/2D_3D_AdLer#194]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] Animierte Texturen z.B. Avatar blinzelt 
- [x] ~~Additive Texturen möglich?~~ <-- Nein

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Ergebnisse der Recherche wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [x] Dokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [ ] Research wurde, falls möglich, in UML Klassendiagrammen bzw. Komponentendiagrammen getestet
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by Lizardguard** [comment]
Wenig hilfreicher forumsbeitrag bezüglich sprites:
https://forum.babylonjs.com/t/possibility-to-put-animated-sprite-as-material-for-box-mesh/6023/9
Playground mit animierten sprite:
https://www.babylonjs-playground.com/#1V3CAT#171
Animation via procedural texturing:
https://doc.babylonjs.com/divingDeeper/materials/using/proceduralTextures
Playground procedural texture animation (Relevant für wasser/feuer/ähnliches):
https://playground.babylonjs.com/#K9GLE6#49
Video Texturen (Relevant für einfache Gesichts animationen?)
https://doc.babylonjs.com/divingDeeper/materials/using/videoTexture
