### ISSUE TITLE
Zenhub/Github Labels anpassen

### ISSUE THREAD

**Issue by Lizardguard** [ProjektAdLer/2D_3D_AdLer#195]
duplicate, enhancement, good first issue, invalid, question und wontfix brauchen wir nicht.
Stattdessen bräuchten wir  'coding', 'design', 'asset' und 'research' tags.

**Comment by DerKatsche** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/195?planning-poker) with ZenHub @LuckyLuke28 @philgei @Lizardguard
