### ISSUE TITLE
Als Studierender ist mir mein Lernziel stets bekannt

### ISSUE THREAD

**Issue by LuckyLuke28** [ProjektAdLer/2D_3D_AdLer#204]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] Es gibt ein Icon für Lernziele 
- [x] Es wird ein Button für Lernziele erzeugt 
- [x] Das Lernziel wird angezeigt
- [x] Der Button ist gestyled
- [x] Die Anzeige ist gestyled
- [x] Es gibt pro Lernraum ein Lernziel (<-- Backend)
- [x] Die API liefert ein Lernziel pro Lernraum 

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist in GitHub
- [x] Die Codekonventionen sind eingehalten
- [x] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [ ] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [ ] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert falls nötig
- [ ] Changelog des jeweiligen Release wurde aktualisiert, falls erforderlich (Wiki)
- [x] Es gibt keine bekannten Bugs
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by Lizardguard** [comment]
@philgei 
Es ist jetzt auf unserer seite tatsächlich alles erledigt. 
Mit dem Fake backend wird alles korrekt angezeigt. Jetzt muss nur noch was von moodle kommen :)
