### ISSUE TITLE
Als Lernender möchte ich 2D Lernelemente starten und Punkte erhalten

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#22]
**User Story**
Als Lernender möchte ich Aufgaben bearbeiten und Punkte erhalten

**Aktzeptanzkriterien**
- [x] Spieler können Punkte pro Lernraum sammeln
- [x] Lernelemente können Punkte für ihren Lernraum hinzufügen
- [x] Punktestand ist auslesbar (z.B. über interne API)
- [x] Pro geöffnetes Lernelement gibt es Punkte

**Definition of Ready** 
- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen 

**Definition of Done** 
- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen 
- [x] Die Implementierung ist in GitHub 
- [x] Eine Code Review wurrde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 92% sein 
- [ ] Alle Tests müssen bestanden sein 
- [ ] Benutzerdokumentation angelegt (Handbuch)
- [ ] Technische Dokumentation angelegt (ZenHub) 
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell 
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode) 
- [x] Changelog angelegt 
- [x] Es gibt keine bekannten Bugs

**Comment by DerKatsche** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/22?planning-poker) with ZenHub @AdLer-Lukas @Lizardguard
