### ISSUE TITLE
Testing: Babylon Controller

### ISSUE THREAD

**Issue by Lizardguard** [ProjektAdLer/2D_3D_AdLer#242]
**User Story**

Verbleibende ungetestete Babylon Controller:
> src/Components/Core/Presentation/Babylon/

**Akzeptanzkriterien**

- [x] Avatar/AvatarController
- [x] LearningElement/LearningElementController

**Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden Beteiligten klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Implementierung ist gepusht
- [ ] Die Codekonventionen sind eingehalten
- [ ] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [ ] Unittestabdeckung ist über 92% oder so hoch wie möglich mit validen Gründen weshalb die 92% nicht erreicht werden können
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [ ] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [ ] Es gibt keine bekannten Bugs
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by DerKatsche** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/242?planning-poker) with ZenHub @philgei
