### ISSUE TITLE
Backend: Kurs durch Backup erstellen

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/2D_3D_AdLer#256]
Es muss durch Upload eines .mbz files seitens AMG ein Kurs erstellt und gespeichert werden

- [x] File Hochladen
- [x] File Entpacken
- [x] H5P Dateien aus der Datei lesen
- [x] Kurs in der Datenbank erstellen
- [x] CRUD Operationen für alle Kurse
- [x] Testabdeckung 92%

**Comment by splican** [comment]
Akzeptanzkriterien: [x] - Erledigt
