### ISSUE TITLE
Backend: Erlangen von Nutzerinformationen

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/2D_3D_AdLer#258]
Nutzerinfomrationen müssen mit Angabe eines Token erlangt werden. Dazu zählen:

- [x] UserName
- [x] Id
- [x] Ist der Nutzer ein Admin
- [x] Testabdeckung 92%

**Comment by splican** [comment]
Akzeptanzkriterien:
- [x] Erledigt
