### ISSUE TITLE
Menu - Title Bar

### ISSUE THREAD

**Issue by Lizardguard** [ProjektAdLer/2D_3D_AdLer#268]
**User Story**

Als user möchte ich im Menü eine Kopfzeile sehen, die mir angibt wo im Menu ich gerade bin (Titel) Sowie Navigationsmöglichkeiten bietet (Burger)

**Akzeptanzkriterien**

- [x] Titel 
- [x] Burger Menu Button
- [x] Controller, Viewmodel, Presenter
- [x] back Button (falls nicht im hauptmenu)
- [x] Styling

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist gepusht
- [x] Die Codekonventionen sind eingehalten
- [x] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [x] Unittestabdeckung muss größer 92% sein
- [x] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [ ] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [ ] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert falls nötig
- [ ] Changelog des jeweiligen Release wurde aktualisiert, falls erforderlich (Wiki)
- [x] Es gibt keine bekannten Bugs
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/268?planning-poker) with Zenhub @DerKatsche @Lizardguard @philgei @splican

**Comment by splican** [comment]
Folgetask: #295
