### ISSUE TITLE
Menu - LearningRoomSelection

### ISSUE THREAD

**Issue by Lizardguard** [ProjektAdLer/2D_3D_AdLer#271]
**User Story**

Als user möchte ich in einer graphischen Darstellung meiner Lernwelt einen Lernraum auswählen können

**Akzeptanzkriterien**

- [x] Anzeige einer Liste
- [x] Backend (oder MockBackend) beinhaltet eine Lernwelt mit Pfaden
- [ ] optional: Graph wird stattdessen korrekt angezeigt
- [x] UseCase zu "Lernräume aus Lernwelt auslesen"
- [x] Styling

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist gepusht
- [x] Die Codekonventionen sind eingehalten
- [x] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [x] Unittestabdeckung muss größer 92% sein
- [x] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [ ] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [ ] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert falls nötig
- [ ] Changelog des jeweiligen Release wurde aktualisiert, falls erforderlich (Wiki)
- [x] Es gibt keine bekannten Bugs
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/271?planning-poker) with Zenhub @DerKatsche @Lizardguard @philgei @splican

**Comment by splican** [comment]
Folgetask: #295
