### ISSUE TITLE
React Router Research

### ISSUE THREAD

**Issue by Lizardguard** [ProjektAdLer/2D_3D_AdLer#279]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] React Router wurden recherchiert

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Ergebnisse der Recherche wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [x] Dokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [x] Research wurde, falls möglich, in UML Klassendiagrammen bzw. Komponentendiagrammen getestet
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by Lizardguard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/279?planning-poker) with Zenhub @DerKatsche @LuckyLuke28 @philgei @splican

**Comment by Lizardguard** [comment]
Also, quellen:
https://reactrouter.com/en/main/getting-started/tutorial
und 
https://www.pluralsight.com/guides/react-router-typescript

Bezüglich Aufbau, simples beispiel siehe bild:
![image](https://user-images.githubusercontent.com/24432852/189186025-85e19603-498c-40b0-84ba-589716fcb544.png)

Zum Switchen zwischen den routes kann (bspw) folgendes genutzt werden, aber die zurück funktion des browsers geht eben auch.
![image](https://user-images.githubusercontent.com/24432852/189186376-353c9367-7a00-4a73-b467-634ae88ba7c8.png)

**Comment by Lizardguard** [comment]
Beispiel wie man learning worlds oder räume mit in die url packen kann:
![image](https://user-images.githubusercontent.com/24432852/189187799-44f5face-06fa-4187-ac54-255a2dbf4993.png)

**Comment by DerKatsche** [comment]
Dependency von React Router: https://github.com/remix-run/history/tree/main/docs
