### ISSUE TITLE
PDF als Lernelement integrieren

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#348]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] Möglichkeiten zur PDF Einbindung recherchieren (React Component)
- [ ] ~~Umsetzungsaufwand abschätzen (bis Evaluation möglich?)~~
- [x] Test ob es auf allen Browsern/Geräte korrekt dargestellt wird

**Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden Beteiligten klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Ergebnisse der Recherche wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [ ] Dokumentation wurde, falls nötig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [ ] Research wurde, falls möglich, in UML Klassendiagrammen bzw. Komponentendiagrammen getestet
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/348?planning-poker) with Zenhub @DerKatsche @Lizardguard @philgei @splican

**Comment by DerKatsche** [comment]
Vorläufige Recherche-Ergebnisse:
# react-pdf
- einfaches Package zum Laden und Anzeigen von PDFs in React
- Erweiterung von PDF.js für Nutzung in React
- Document und Page als praktische React Komponenten
- markierbarer Text, teilweise janky durch drübergelegte Text Ebene
- keine UI
- Inhaltsverzeichnis
- einfache Bedienung

# PDF.js
- Package zum Laden und Anzeigen von PDFs in JS

# React-PDF-Viewer
- kostenpflichtig (199 Dollar für unbegrenzte Entwickler)

# pspdfkit
- kostenpflichtig (Preis nach Kontakt)

# Browser-eigener Viewer

**Comment by DerKatsche** [comment]
Wir sollten PDFObject verwenden
