### ISSUE TITLE
Evaluationsablauf codifizieren

### ISSUE THREAD

**Issue by Lizardguard** [ProjektAdLer/2D_3D_AdLer#386]
**User Story**

Den Profs eine dedizierte Anleitung geben mit Timetables und Deadlines wann wir was brauchen zur Durchführung einer geplanten Evaluation.

**Akzeptanzkriterien**

- [x] Wiki Seite erstellt
- [x] Wiki Seite mit allen Profs kommuniziert

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Ergebnisse der Recherche wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [ ] Dokumentation wurde, falls nötig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [ ] Research wurde, falls möglich, in UML Klassendiagrammen bzw. Komponentendiagrammen getestet
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/386?planning-poker) with Zenhub @DerKatsche @Lizardguard @philgei @splican

**Comment by DerKatsche** [comment]
https://wiki.projekt-adler.eu/de/Evaluation/Evaluationsablauf
