### ISSUE TITLE
Avatar Steuerung polishen

### ISSUE THREAD

**Issue by DerKatsche** [ProjektAdLer/2D_3D_AdLer#391]
**Technical Story**

Wenn die Kamera wieder drehbar ist, muss die Steuerung auch auf Mobilgeräten funktionieren.

**Akzeptanzkriterien**

- [x] Mouse/Touch Steuerung auf Mobil überprüft

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [ ] Requirements sind erstellt/angepasst und auf Writerside dokumentiert
- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Implementierung ist gepusht
- [ ] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [ ] Unittests sind erstellt
- [ ] Alle Tests müssen bestanden sein
- [ ] Benutzerdokumentation wurde angelegt oder angepasst (Writerside)
- [ ] Changelog des jeweiligen Release wurde aktualisiert
- [ ] Es gibt keine bekannten Bugs oder für Bug wurde Issue erstellt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [ ] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)
- [ ] [Optional] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/391?planning-poker) with Zenhub @DerKatsche @Lizardguard @philgei @splican
