### ISSUE TITLE
Durchstich A-Frame

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#4]
Als Entwickler brauchen wir einen Prototypen mit A-Frame, sodass eine Vergleichbarkeit zu Babylon.js gegeben ist. 

**Aktzeptanzkriterien**
- [x] Single Choice Frage aus Moodle wird Live abgefragt
- [x] Frage aus Moodle wird bei jedem neuen Versuch angezeigt (Text auf 3D Panel)
- [ ] Visuelles Feedback bei Beantwortung der Fragen (Icon und farbig blinken)
- [x] Youtube-Video wird angezeigt
- [x] Youtube-Video ist interagierbar
- [x] Bei richtiger Beantwortung soll sich die Türe öffnen
- [ ] Bei beenden soll die Szene neu geladen (geresettet) werden
- [x] WASD - Steuerung
- [ ] Licht ausfaden (dunkler werden) 
- [x] Kamera ausfaden
- [ ] Buttons animieren
- [x] Tutorial Text
- [x] Fadenkreuz
- [ ] Rendertarget soll responsive sein
- [x] UI-Elemente sollen responsive sein

**Definition of Ready** 
- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen 

**Definition of Done** 
- [ ] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen 
- [x] Die Implementierung ist in GitHub 
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [ ] Es soll Unit Tests geben
- [x] Alle Tests müssen bestanden sein 
- [x] Benutzerdokumentation angelegt (Readme)
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)

**Comment by philgei** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/4?planning-poker) with ZenHub @AdLer-Lukas @DerKatsche @Lizardguard
