### ISSUE TITLE
Grundstruktur Lernpfad-Node-Darstellung für Lernraummenü

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#421]
**User Story**

Als Nutzer möchte ich die Lernpfade in einer Node-Darstellung angezeigt bekommen, um eine gute Übersicht über die Lernwelt und den aktuellen Lernfortschritt zu haben. 

**Akzeptanzkriterien**

- [x] Graph Ansicht in Space Selection eingebunden 
- [x] ~~Custom Nodes für UND/ODER Nodes erstellt~~ SpaceNode um Handler erweitert
- [x] Custom Node für Space Nodes erstellt 
- [x] Space Nodes sind klickbar und öffnen die jeweilige SpaceDetail
- [x] Simpler Algorithmus für Layout der Nodes implementiert 
- [x] Nutzersteuerung eingeschränkt auf gewünschte Interaktionen 
- [x] Teststrategie festgelegt

**Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden beteiligten Entwickler klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Implementierung ist gepusht
- [ ] Die Codekonventionen sind eingehalten
- [ ] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [ ] Unittestabdeckung muss größer 92% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [ ] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [ ] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert falls nötig
- [ ] Changelog des jeweiligen Release wurde aktualisiert, falls erforderlich (Wiki)
- [ ] Es gibt keine bekannten Bugs
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by DerKatsche** [comment]
ReactFlow - Notizen
zusammenstellen der Nodestruktur sieht einfach aus
Handler für Klickevents einfahc einzubinden
evtl. CustomNode benötigt um Styling an den Rest von AdLer anzupassen
Styling Guide: https://reactflow.dev/docs/guides/theming/
Tailwind Styling Beispiel: https://reactflow.dev/docs/examples/styling/tailwind/
vermutlich CustomNodes für UND/ODER- und Space-Nodes benötigt
Setup für Testing mit Jest benötigt: https://reactflow.dev/docs/guides/testing/
Beschränkung der Nutzersteuerung nötig (standardmäßig sehr interaktiv, z.B. Verschieben von Nodes etc)
Credit benötigt ohne PRO (https://reactflow.dev/docs/guides/remove-attribution/)
Graph Darstellung
Algorithmus für Errechnung der Nodepositionen muss gefunden werden
abhängig von den Lernpfaden die Autoren liefern
wahrscheinlich nicht alle Algorithmen für alle Graphen anwendbar

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/421?planning-poker) with Zenhub @DerKatsche @Lizardguard

**Comment by DerKatsche** [comment]
Aufwand auf 3 reduziert
