### ISSUE TITLE
"Goals" sind jetzt Arrays

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/2D_3D_AdLer#440]
Alle Goals (also Element, Raum und Weltziele) sind nun als String Array vorhanden und müssen dementsprechend umgeschrieben werden.

Momentan wird im Backend Adapter nur der erste Platz des Arrays in die alten Goals geschrieben

**Akzeptanzkriterien**

- [x] Datentyp in allen TOs und UseCases ändern 
- [x] React Komponenten zeigen neue Daten an 
- [x] Backend Adapter gibt alle Ziele weiter 
- [x] Lernziele als Liste stylen

**Definition of Ready**

- [ ] User Story ist klein genug f?r Sprint
- [ ] User Story ist f?r jeden beteiligten Entwickler klar verst?ndlich
- [ ] User Story Aufwand ist gesch?tzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert f?r das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erf?llt
- [ ] Die Implementierung ist gepusht
- [ ] Die Codekonventionen sind eingehalten
- [ ] Eine Code Review wurde durchgef?hrt (oder in Paired Programming gearbeitet)
- [ ] Unittestabdeckung muss gr??er 92% sein
- [ ] Alle Tests m?ssen bestanden sein
- [ ] Technische Dokumentation innerhalb der Realisierung wurde, falls n?tig, erstellt (Quellcode)
- [ ] Benutzerdokumentation wurde, falls n?tig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde, falls n?tig, angelegt (Zenhub Kommentar)
- [ ] UML Aktivit?tsdiagramm wurde erstellt bzw. aktualisiert falls n?tig
- [ ] Changelog des jeweiligen Release wurde aktualisiert, falls erforderlich (Wiki)
- [ ] Es gibt keine bekannten Bugs
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/440?planning-poker) with Zenhub @DerKatsche @philgei @splican
