### ISSUE TITLE
Themes in Adler Engine 1.1. integrieren 

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#549]
**User Story**

Der Autor möchte abwechslungsreiche Lernräume erstellen, die dem Nutzer angezeigt werden. 
Hierfür können für jeden Grundriss verschiedene Themes angewandt werden. 
Für Lernelemente kann der Autor entweder ein spezifisches Modell aus den dem Spacetheme zugeordneten selbst auswählen oder abhängig vom Lernelement Typ zufällig ein Modell anzeigen lassen. 

**Akzeptanzkriterien**

- [x] Abstimmung mit Niklas und Entwicklern ist erfolgt
- [x] Themes unterscheiden sich nach Texturen und Deko
- [x] Die Themes wurden mit Didaktik und AMG abgestimmt
- [x] Alle erforderlichen GLB liegen in den Assets 
- [x] Das Datenfeld Theme aus der AWF 0.4 kann verarbeitet werden 
- [ ] Ausgewählte Themes aus dem Autorentool werden korrekt in Adler Engine angezeigt 
- [x] Theme "Default" abgeschlossen
- [x] Theme "Arcade" abgeschlosse
- [x] Theme "Campus" abgeschlossen
- [ ] ~~Theme "Büro" abgeschlossen~~

**Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden beteiligten Entwickler klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Assets sind in GitHub bzw. auf Zugriffsbereit auf dem Fileserver vorhanden
- [ ] Eine Asset Review wurde durchgeführt (oder in Paired Modelling(?) gearbeitet)
- [ ] Alle Tests müssen mit dem Asset in der Szene bestanden sein
- [ ] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [ ] Changelog des jeweiligen Release wurde aktualisiert (Wiki)
- [ ] Es gibt keine bekannten Bugs
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/549?planning-poker) with Zenhub @DerKatsche @Grunick @Lizardguard @mountler @Payloo
