### ISSUE TITLE
Informationsdialog in AdLer Engine designen 

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#551]
**User Story**

Als Nutzer möchte ich Hinweise vom System auf meine Interaktionen erhalten 

**Akzeptanzkriterien**

- [x] Mögliche Hinweise/Dialoge sind bekannt 
- [x] Grafische Umsetzung der Hinweise wird entworfen 
- [x] Umsetzung wird im Team abgestimmt 
- [x] Umsetzung wird dokumentiert

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Ergebnisse der Recherche wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [x] Dokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [ ] Research wurde, falls möglich, in UML Klassendiagrammen bzw. Komponentendiagrammen getestet
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/551?planning-poker) with Zenhub @DerKatsche @Grunick @Lizardguard @Payloo @splican

**Comment by splican** [comment]
https://wiki.projekt-adler.eu/de/AdLerEngine/Design/Informationsdialog
