### ISSUE TITLE
Ausgewähltes 3D Modell aus Autorentool wird nicht in AdLer Engine dargestellt

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#553]
**User Story**

In der DSL wird das ausgewählte 3D Modell aus dem Autorentool korrekt übermittelt.

Ein 3D-Modell für ein H5P wurde im Autorentool ausgewählt. Es ist auch richtig in der DSL vorhanden "drawingtable"... in AdLerEngine wird als Spielautomat dargestellt.

MKD26: Lernwelt Paris, Lernraum 3, Lernelement "2_Funktionen der Kamera 1"

**Akzeptanzkriterien**

- [x] Modell wird richtig angezeigt
- [x] Herausgefunden, wo/wie auf die mkd26 Welten zugegriffen werden kann
- [x] atf Files der einzelnen mkd26 Lernwelten extrahieren und auf Cloud ablegen

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist gepusht
- [x] Die Codekonventionen sind eingehalten
- [x] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [x] Unittestabdeckung muss größer 92% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [x] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [x] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert falls nötig
- [x] Changelog des jeweiligen Release wurde aktualisiert, falls erforderlich (Wiki)
- [x] Es gibt keine bekannten Bugs
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by Lizardguard** [comment]
Also... 
Fehlersuche:
[x] Checken der Einbindungsstrings von Modellen in Babylon/LearningElementsView
[x] Checken ob es ein default gibt (gibt es nicht)
[x] Suche nach Zugang für MKD26 Welten (Zugang zu diesem Kurs: Username:testUser5 PW:userName5%
[x] Suche nach was genau aus der Welt übertragen wird (ATF auf dem echten Stand)
https://cdn.discordapp.com/attachments/887582352560246804/1130796214858825758/image.png
[x] Suche nach Übersetzung von 'h5p_blackboard'.
-> Blackboard ist weder Slotmachine noch drawing table.

????

**Comment by Lizardguard** [comment]
Blackboard war in unserem code als backboard hinterlegt, wurde daher nicht erkannt und wurde dann random gesetzt.

Sollte nun behoben sein.

**Comment by Lizardguard** [comment]
Cloud mit welten:
https://cloud.projekt-adler.eu/s/gZoqRHfb7aBEfNy
