### ISSUE TITLE
Technisches Konzept Adaptivitäts-Element mit anderen Teams festlegen 

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#560]
**User Story**

Um eine robuste Umsetzung von Adaptivität zu gewährleisten, ist es erforderlich ein gemeinsames Verständnis auf ein Technisches Konzept zu entwickeln und Schnittstellen zu schaffen, um regelmäßigen Austausch zu gewährleisten. 

**Akzeptanzkriterien**

- [x] Ansprechperson in anderen Teams bekannt
- [x] Meeting mit allen betreffenden Personen geplant und durchgeführt
- [x] Kommunikation mit Backend abgesteckt
- [x] zu erhebende Datenpunkte priorisiert
- [x] Struktur der Auswertungslogik festgelegt

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Ergebnisse der Recherche wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [ ] Dokumentation wurde, falls nötig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [ ] Research wurde, falls möglich, in UML Klassendiagrammen bzw. Komponentendiagrammen getestet
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/560?planning-poker) with Zenhub @DerKatsche @Grunick @Lizardguard @mountler @Payloo
