### ISSUE TITLE
Ausstehende Assets für Quiz (Adaptivitäts) Element erstellen

### ISSUE THREAD

**Issue by Lizardguard** [ProjektAdLer/2D_3D_AdLer#597]
**User Story**

**Akzeptanzkriterien**

- [x] 2D Icon
- [x] 3D Icon
- [x] 2D Rendering of NPC (Sherriff Justice) for close up

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Assets sind in GitHub bzw. auf Zugriffsbereit auf dem Fileserver vorhanden
- [ ] Eine Asset Review wurde durchgeführt (oder in Paired Modelling(?) gearbeitet)
- [ ] Alle Tests müssen mit dem Asset in der Szene bestanden sein
- [ ] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [ ] Changelog des jeweiligen Release wurde aktualisiert (Wiki)
- [ ] Es gibt keine bekannten Bugs
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by splican** [comment]
2D Icon:
https://cloud.projekt-adler.eu/f/34488
