### ISSUE TITLE
TextComponent/ QuizComponent gibt index.html-Datei statt Dateiinhalt zurück

### ISSUE THREAD

**Issue by mountler** [ProjektAdLer/2D_3D_AdLer#603]
**User Story**

Nach mehrmaligen hintereinander anklicken von TextComponent und QuizComponent wird statt der eigentlichen Textdatei der Inhalt der index.html-Datei angezeigt.

**Akzeptanzkriterien**

- [x] Probleme identifiziert 
- [x] Probleme behoben

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist gepusht
- [x] Die Codekonventionen sind eingehalten
- [x] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [x] Unittestabdeckung muss größer 92% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [x] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [x] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert falls nötig
- [x] Changelog des jeweiligen Release wurde aktualisiert, falls erforderlich (Wiki)
- [x] Es gibt keine bekannten Bugs
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by mountler** [comment]
![Bug_QuizComponente_TextComponente.png](https://images.zenhubusercontent.com/64a94f2a21cd256879821c1a/d0906e39-41f6-4aab-8164-3b789df02922)

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/603?planning-poker) with Zenhub @DerKatsche @Grunick @Lizardguard @mountler @Payloo @splican
