### ISSUE TITLE
Meeting zu Dokumentation 

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#617]
**User Story**

Die Dokumentation zu AdLer Engine ist so ausgearbeitet, dass ein weitere Entwickler damit arbeiten kann und die Anforderungen an die Gesamtdoku des Projekts sichergestellt ist. 

**Akzeptanzkriterien**

- [x] Termin vereinbaren - 31.8. 10:45
- [x] Meeting durchführen 
- [x] Ergebnisse dokumentieren

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Ergebnisse der Recherche wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [x] Dokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [x] Research wurde, falls möglich, in UML Klassendiagrammen bzw. Komponentendiagrammen getestet
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/617?planning-poker) with Zenhub @DerKatsche @Grunick @Lizardguard @mountler @Payloo @splican

**Comment by mountler** [comment]
Dokumentations-Link:
https://cloud.projekt-adler.eu/apps/files/?dir=/AdLer/Entwicklung/Software%20Entwicklung/Leitf%C3%A4den%20Anleitungen%20Richtlinien&fileid=42319
