### ISSUE TITLE
[Research] - TH AB Videoserver verbietet Zugriff aus AdLerEngine 

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#624]
**Technical Story**

Auf Videos vom THAB Videoserver kann nicht zugegriffen werden.

**Akzeptanzkriterien**

- [x] Recherche woran liegt es
- [x] Lösungsvorschlag in Comment
- [x] Antwort von Raphael erhalten und in Kommentar dokumentiert
- [x] Folgetask zur Implementierung erstellen aus Lösungsvorschlag

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden Beteiligten klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Researchergebnisse sind als ZenHub Kommentar dokumentiert (Wiki / MuralBoard / etc.)
- [ ] Die Realisierung wurde erfolgreich durch den Product Owner abgenommen
- [ ] [Optional] Dokumentation des Vorgehens oder externer Quellen wurde angelegt (Zenhub Kommentar)

**Comment by splican** [comment]
Dazu passendes Testvideo: https://video.th-ab.de/paella/ui/watch.html?id=345eadbf-f9b9-4a61-82d4-f8258c2e00c1

**Comment by DerKatsche** [comment]
Scheinbar je nach Konfiguration/Freigabe auf Seite des Videoservers sind manche Videos für jeden zugänglich ODER nur für angemeldete Mitglieder der TH AB.

Falls Video nur mit Anmeldung verfügbar:
- in iframe eingebundenes Video versucht auf Anmeldemaske unter https://idpc.th-ab.de/ umzuleiten
- https://idpc.th-ab.de/ blockt die Einbindung in einem iframe wegen Content Security Policy directive: "frame-ancestors *.th-ab.de"

**Comment by DerKatsche** [comment]
Mögliche Lösungsansätze (in verschiedenen Kombinationen anwendbar):
1. Autoren müssen Video richtig freigeben, damit es angezeigt werden kann
2. statt Anmeldemaske in iframe einzubinden, muss der Fehlerfall abgefangen und auf einen neuen Tab umgeleitet werden
3. mindestens sollte in Video-Lernelement ein sinnvoller Fehler für dei Nutzenden angezeigt werden (z.B. "Video kann nicht geladen werden. Bitte wenden Sie sich an Ihren Prof/Tutor.")
