### ISSUE TITLE
H5P UI Library

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#699]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] H5P Standalone Bibliothek updaten
- [x] Ergebnis dokumentieren in Kommentar im Task

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Ergebnisse der Recherche wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [x] Dokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [x] Research wurde, falls möglich, in UML Klassendiagrammen bzw. Komponentendiagrammen getestet
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by philgei** [comment]
Lib ist geupdatet. An sich bringt das keine (direkten neuerungen). Allerdings hat sie sich unter der Haube komplett verändert.

Problem, warum es so lange dauert hat:

1. H5P hat basis-klassen, die nicht über npm installiert werden (können). Diese hab ich bei meinem Struggle gestern sehr lange nicht aktuallisiert, was Fehler geworfen hat.
2. Die neue Version sieht "http://locahlost..." nicht als URL an, wesshalb fehler beim fetching entstehen. Die lösung war es, dynamisch ""http://locahlost..." mit "//locahlost..." zu ersetzen. Diese lösung muss stand jetzt leider im prod code leben. Sollte aber kein Problem darstellen.
