### ISSUE TITLE
Buttonklick auf Rand wird nicht registriert

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#702]
**User Story**

Liegt an der Verschiebung des Containers beim Drücken des Buttons

**Akzeptanzkriterien**

- [x] Buttonklick fixen 

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Ergebnisse der Recherche wurden von mindestens einer anderen Person gereviewt (oder in Paired Researching gearbeitet)
- [x] Dokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [x] Research wurde, falls möglich, in UML Klassendiagrammen bzw. Komponentendiagrammen getestet
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by DerKatsche** [comment]
https://css-tricks.com/video-screencasts/123-if-it-moves-when-you-click-make-something-stick/
