### ISSUE TITLE
Evaluate catch blocks for each error.

### ISSUE THREAD

**Issue by Lizardguard** [ProjektAdLer/2D_3D_AdLer#710]
**User Story**

Wir brauchen Catch blöcke für jeden Error der geworfen werden kann (primär innerhalb der usecases, aber prinzipiell für alle throw Errors).

**Akzeptanzkriterien**

- [x] Task überprüfen: Falls nicht mehr relevant, alle Kriterien durchstreichen und auf Done schieben und/oder neuen Task erstellen, falls wieder etwas relevantes entsteht
- [x] Folgende Liste überprüfen / überarbeiten
- [x] DisplayLearningElementusecase
- [x] GetAdaptivityElementStatusUseCase
- [x] LoadAdaptivityElementUseCase
- [x] LoadExternalLearningElementUseCase
- [x] SubmitAdaptivityElementSelectionUseCase
- [x] CalculateLearningSpaceAvailabilityUseCase
- [x] CalculateLearningSpaceScoreUseCase
- [x] CalculateLearningWorldScoreUseCase
- [x] GetLearningSpacePrecursorAndSuccessorUseCase
- [x] GetLoginStatusUseCase
- [x] GetUserLocationUseCase
- [x] LoadLearningElementUseCase
- [x] ~~LoadStoryElementUseCase~~
- [x] ~~LogoutUseCase~~
- [x] ScoreH5PLearningElementUseCase

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Implementierung ist gepusht
- [ ] Die Codekonventionen sind eingehalten
- [ ] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [ ] Unittestabdeckung muss größer 92% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [ ] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [ ] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert falls nötig
- [ ] Changelog des jeweiligen Release wurde aktualisiert, falls erforderlich (Wiki)
- [ ] Es gibt keine bekannten Bugs
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/710?planning-poker) with Zenhub @DerKatsche @Grunick @Lizardguard
