### ISSUE TITLE
Sonar einrichten

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/2D_3D_AdLer#72]
**User Story**
Zur Sicherstellung der Coding Guidelines und zum erstellen von guten Code soll Sonar als Statische Code Analyse eingerichtet werden.

**Aktzeptanzkriterien**
- [x] Sonar mit unseren Regeln konfigurieren
- [x] Git Repo mit SonarCloud verbinden
- [x] Coding Regeln erstellen
- [x] Sonar linter für VSCode einrichten
- [x] Wiki eintrag für SonarLint
- [x] Wiki Eintrag für SonarCloud + Github
- [x] Wiki Eintrag für Arbeiten mit Sonar

**Definition of Ready** 
- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen 

**Definition of Done** 
- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen 
- [ ] Die Implementierung ist in GitHub 
- [ ] Eine Code Review wurrde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 92% sein 
- [ ] Alle Tests müssen bestanden sein 
- [ ] Benutzerdokumentation angelegt (Handbuch)
- [ ] Technische Dokumentation angelegt (ZenHub) 
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell 
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode) 
- [ ] Changelog angelegt 
- [ ] Es gibt keine bekannten Bugs

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/72?planning-poker) with ZenHub @DerKatsche @Lizardguard @philgei
