### ISSUE TITLE
3D Avatar bleibt hängen und Lernraum muss neugestartet werden

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#733]
**User Story**

Aktuell kommt es häufig vor, dass der 3D Avatar hängen bleibt und der Lernraum nicht mehr bedienbar ist. 
Erst ein Wechsel in das Lernraum Menü und erneutes Betreten der Lernraums löst das Problem. 
Wobei der Avatar immer wieder hängen bleiben kann

**Akzeptanzkriterien**

- [x] Fehler ist identifiziert
- [x] 3D Avatar bleibt in keiner Situation hängen

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Implementierung ist gepusht
- [x] Die Codekonventionen sind eingehalten
- [x] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [x] Unittestabdeckung muss größer 92% sein
- [x] Alle Tests müssen bestanden sein
- [x] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [x] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [x] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [x] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert falls nötig
- [x] Changelog des jeweiligen Release wurde aktualisiert, falls erforderlich (Wiki)
- [x] Es gibt keine bekannten Bugs
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by Lizardguard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/733?planning-poker) with Zenhub @Lizardguard @Grunick @mountler @AdLer-Lukas
