### ISSUE TITLE
[Bug] - Navmesh reicht unter 3D Modelle, die nicht auf Bodenhöhe platziert sind

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#739]
**Beschreibung des Problems:**

Bilder, die für eine Nutzung an der Wand gedacht sind, aber in der Raummitte stehen, können vom Spieler Charakter durchlaufen werden. 

**Erwartetes Verhalten:**

Charakter kann nicht durch Lernelemente laufen.

**Tatsächliches Verhalten:**

Charakter kann duch bestimmte Lernelemente laufen.

**Ansprechpartner:**

Marius

**Ursache (erst bei Fix angeben):**

(wird durch Team 3D ausgefüllt)

**Lösung (erst bei Fix angeben):**

(wird durch Team 3D ausgefüllt)

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/739?planning-poker) with Zenhub @DerKatsche @Grunick @Lizardguard
