### ISSUE TITLE
Prettier config erstellen + ignore

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/2D_3D_AdLer#74]
**User Story**
Als Entwickler möchte ich die selbe Prettier file wie alle anderen Entwickler haben.

**Aktzeptanzkriterien**
- [x] Jeder muss mit den Einstellungen vertraut sein und diese für ok befinden
- [ ] Prettier ist mit Sonar verbunden
- [x] Eine Prettier Config muss erstellt sein

**Definition of Ready** 
- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)

**Definition of Done** 
- [ ] Alle Akzeptanzkriterien sind erfüllt
- [x] Jeder muss die Einstellungen bei sich eingerichtet haben
- [x] Die Implementierung ist in GitHub 
- [ ] Benutzerdokumentation angelegt (Handbuch)
- [ ] Technische Dokumentation angelegt (ZenHub)

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/74?planning-poker) with ZenHub @DerKatsche @Lizardguard @philgei
