### ISSUE TITLE
Dokumentation - Lernwelt - Laden, betreten, verlassen

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#754]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [ ] Akzeptanzkriterium

**Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden beteiligten Entwickler klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] ZenHub Tasks sind gecheckt
- [ ] Wiki ist gecheckt
- [ ] Anforderungen mit IDs sind erstellt
- [ ] Aktivitätsdiagramm (falls nötig) ist erstellt
- [ ] Unit-Tests sind zugewiesen
- [ ] Fehlende Unit-Tests sind dokumentiert
- [x] Review wurde durchgeführt

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/754?planning-poker) with Zenhub @DerKatsche @Lizardguard @mountler
