### ISSUE TITLE
Dokumentation - Externes Lernelement Adapitivität

### ISSUE THREAD

**Issue by splican** [ProjektAdLer/2D_3D_AdLer#759]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] Writerside Artikel geschrieben
- [x] Tests verlinkt

**Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden beteiligten Entwickler klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] ZenHub Tasks sind gecheckt
- [ ] Wiki ist gecheckt
- [ ] Anforderungen mit IDs sind erstellt
- [ ] Glossar verlinkt und gegebenenfalls erweitert
- [ ] Aktivitätsdiagramm (falls nötig) ist erstellt
- [ ] Unit-Tests sind zugewiesen
- [ ] Fehlende Unit-Tests sind dokumentiert
- [ ] Review wurde durchgeführt

**Comment by mountler** [comment]
https://projektadler.github.io/Documentation/ewe0044.html
https://projektadler.github.io/Documentation/ewe0045.html
