### ISSUE TITLE
Die LTI Schnittstelle zu Moodle soll erforscht werden

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/2D_3D_AdLer#79]
**User Story**

Moodle bietet die LTI schnitstelle, welche für den Austausch zwischen Moodle und einem Externen "Software" sorgt. Dieses Muss erforscht und für unsere Zwecke evaluiert werden.

**Akzeptanzkriterien**

- [x] Überblick über LTI im Wiki
- [x] Relevante Funktionen von LTI im Wiki

 

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen

 

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [ ] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Benutzerdokumentation angelegt (Handbuch)
- [ ] Technische Dokumentation angelegt (ZenHub)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/79?planning-poker) with ZenHub @DerKatsche @Lizardguard @philgei

**Comment by DerKatsche** [comment]
An HiWis deligiert
