### ISSUE TITLE
Konzept für Server Infrastruktur aufstellen.

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/2D_3D_AdLer#80]
**User Story**
Zurm bereitstellen der AdLer Engine benötigt es Infrastruktur. Diese kann evtl. mittels einer Kombination aus Moodle, WebServer, Datenbank und einem CDN aufgebaut werden. Es gild diese zu Erforschen und auf Eignung zu prüfen. Vor allem mit hinblick auf: 

Einfachheit der Einrichtung
Benutzung mit der AdLer Engine
Benutzung für Team-AMG

**Akzeptanzkriterien**

- [x] Beschreibung der Infrastruktur im Wiki
- [x] Eigung ist mit Team AMG besprochen
- [x] Eignung ist mit Team 3D besprochen

 

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen

 

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [ ] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten
- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Benutzerdokumentation angelegt (Handbuch)
- [ ] Technische Dokumentation angelegt (ZenHub)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/80?planning-poker) with ZenHub @DerKatsche @Lizardguard @philgei
