### ISSUE TITLE
Abstimmung mit Team Evaluation

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#82]
**User Story**

Als Entwicklungsteam der AdLer Engine müssen wir eine enge und abgestimmte Kooperation mit dem Team Evaluation planen, um die im Projektantrag geforderte Nutzerzentrierung sicherzustellen. 

**Akzeptanzkriterien**

- [x] Meeting mit Marco planen 
- [x] Meeting mit Marco durchführen 
- [x] Kooperationsdokument erstellen und kommunizieren

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen

 

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by Lizardguard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/82?planning-poker) with ZenHub @AdLer-Lukas @DerKatsche @philgei
