### ISSUE TITLE
Architektur Template erstellen

### ISSUE THREAD

**Issue by DerKatsche** [ProjektAdLer/2D_3D_AdLer#83]

**Comment by DerKatsche** [comment]
**User Story**

Als Entwickler möchte ich eine neue Komponente per Template hinzufügen können.

**Akzeptanzkriterien**

- [ ] Komponenten Template existiert
- [ ] Template von @Teigler abgenommen

**Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden Beteiligten klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Realease zugewiesen

 

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [ ] Die Implementierung ist in GitHub
- [ ] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [ ] Die Codekonventionen sind eingehalten

- [ ] Unittestabdeckung muss größer 90% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Benutzerdokumentation angelegt (Handbuch)
- [ ] Technische Dokumentation angelegt (ZenHub)
- [ ] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [ ] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Changelog angelegt
- [ ] Es gibt keine bekannten Bugs

**Comment by Lizardguard** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/83?planning-poker) with ZenHub @AdLer-Lukas @philgei @DerKatsche

**Comment by DerKatsche** [comment]
Wiki Einträge:
https://wiki.cluuub.xyz/de/AdLerEngine/Entwicklung/Komponente
https://wiki.cluuub.xyz/de/AdLerEngine/Entwicklung/Repo
