### ISSUE TITLE
Benutzerdokumentation - PB - Lernelement

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#848]
**User Story**

Als _Benutzerrolle_ möchte ich _Funktionalität_ sodass _Wert_ für den Nutzer

**Akzeptanzkriterien**

- [x] Zuerst 3D-Modelle darstellen, danach das Fenster, dass den Inhalt des Lernelements anzeigt 
- [x] Das Fenster mit dem Lernelement Inhalt mit Callouts versehen und diese beschreiben (Überschrift, Inhalt, Schließen) 
- [x] Outlines der Lernelemente erklären (Grün/Rot und Annäherung) 

**Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden beteiligten Entwickler klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] ZenHub Tasks sind gecheckt
- [ ] Wiki ist gecheckt
- [ ] Anforderungen mit IDs sind erstellt
- [ ] Glossar verlinkt und gegebenenfalls erweitert
- [ ] Aktivitätsdiagramm (falls nötig) ist erstellt
- [ ] Unit-Tests sind zugewiesen
- [ ] Fehlende Unit-Tests sind dokumentiert
- [ ] Review wurde durchgeführt

**Comment by splican** [comment]
Die Tabelle mit den 3D-Modellen und Beschreibungen sollte eher als beispielhaft beschrieben werden, da es noch mehr Möglichkeiten gibt. Im Autorentool können verschiedene 3D-Modelle für die einzelnen Lernelemente konfiguriert werden.
