### ISSUE TITLE
Testing Frameworks recherchieren 

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#87]
**User Story**

In der Entwicklung von AdLer sollen Unit Tests für den entstandenen Code geschrieben werden. Dazu wird voraussichtlich ein Testing Framework benötigt. Die Ergebnisse der Recherche sollen auf einer Seite im Wiki festgehalten werden. 

**Akzeptanzkriterien**

- [x] Zusammenfassung der verfügbaren Frameworks vorhanden
- [x] Pro und Contra Punkte zu Frameworks vorhanden
- [x] Begründung für die Auswahl eines der Frameworks vorhanden

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Benutzerdokumentation angelegt (Handbuch)

**Comment by philgei** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/87?planning-poker) with ZenHub @AdLer-Lukas @DerKatsche @Lizardguard

**Comment by DerKatsche** [comment]
Übersicht der Frameworks und Entscheidungsbegründung:
https://wiki.cluuub.xyz/e/de/AdLerEngine/Entwicklung/testFrameworks
