### ISSUE TITLE
Testing Framework in Babylon Komponenten Template integrieren

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#88]
**User Story**

Das Testing Framework für Unit Tests soll in die Babylon und React Komponenten Templates eingebunden werden, um möglichst viel Boilerplate Test Code nicht immer wieder schreiben zu müssen.

**Akzeptanzkriterien**

- [x] Framework in Babylon Komponenten Template eingebunden
- [x] Dokumentation des Frameworks im Wiki

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Die Implementierung ist in GitHub
- [x] Eine Code Review wurde durchgeführt (oder in Pairing Programm erstellt)
- [x] Die Codekonventionen sind eingehalten
- [x] Unittestabdeckung muss größer 90% sein
- [x] Alle Tests müssen bestanden sein
- [x] Benutzerdokumentation angelegt (Handbuch)
- [x] Technische Dokumentation angelegt (ZenHub)
- [x] UML Klassendiagramme und Komponentendiagramme erstellt und aktuell
- [x] Die Dokumentation in der Realisierung wurde erstellt (Quellcode)
- [ ] Es gibt keine bekannten Bugs

**Comment by philgei** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/88?planning-poker) with ZenHub @AdLer-Lukas @DerKatsche @Lizardguard

**Comment by DerKatsche** [comment]
Story Points geändert von 8 auf 21, da Test Coverage und Debugging bei Planung gefehlt hat und Einrichtung schwieriger als erwartet war.
