### ISSUE TITLE
DI Container für JS/TS erforschen

### ISSUE THREAD

**Issue by philgei** [ProjektAdLer/2D_3D_AdLer#89]
Zum erstellen des Templates muss  ein DI Container erforscht werden. Dazu bietet sich InversifyJS an.

Dieses Item muss vor der Erstellen des Template abgeschlossen sein

**Comment by AdLer-Lukas** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/89?planning-poker) with ZenHub @DerKatsche @Lizardguard @philgei
