### ISSUE TITLE
Dokumentation - Presentation Builder 

### ISSUE THREAD

**Issue by DerKatsche** [ProjektAdLer/2D_3D_AdLer#907]
**User Story**

Unsere Variante des Builder Patterns, das für die erstellung der MVC-Klassen verantwortlich ist, muss beschrieben werden.

siehe: https://wiki.projekt-adler.eu/de/AdLerEngine/Entwicklung/PresentationBuilder
Referenz für Builder Pattern: https://refactoring.guru/design-patterns/builder

**Akzeptanzkriterien**

- [x] Funktionalität aus Wikiartikel kurz zusammengefasst
- [x] Diagramm erstellt
- [x] Artikel in Writersite erstellt

**Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden beteiligten Entwickler klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] ZenHub Tasks sind gecheckt
- [ ] Wiki ist gecheckt
- [ ] Anforderungen mit IDs sind erstellt
- [ ] Glossar verlinkt und gegebenenfalls erweitert
- [ ] Aktivitätsdiagramm (falls nötig) ist erstellt
- [ ] Unit-Tests sind zugewiesen
- [ ] Fehlende Unit-Tests sind dokumentiert
- [ ] Review wurde durchgeführt

**Comment by mountler** [comment]
https://projektadler.github.io/Documentation/presentation-builder-engine.html
