### ISSUE TITLE
Dokumentation - 3D Asset Workflow Guide

### ISSUE THREAD

**Issue by Grunick** [ProjektAdLer/2D_3D_AdLer#910]
**User Story**

Erstellen eines Walkthroughs für den Workflow zur Generierung und Einbindung von 3D Assets für Entwickelnde

**Akzeptanzkriterien**

- [x] Prozessbeschreibung zur Erstellung von 3D Assets auf Writerside
- [x] Termin Designer mit Niklas, zur Vorführung des Workflow
- [x] Gegen gecheckt (Mehr Augen Prinzip)
- [x] Commited
- [x] Screencast durchgearbeitet und Informationen externalisiert (Wiki Link siehe Kommentar)

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden beteiligten Entwickler klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Assets sind in GitHub bzw. auf Zugriffsbereit auf dem Fileserver vorhanden
- [ ] Eine Asset Review wurde durchgeführt (oder in Paired Modelling(?) gearbeitet)
- [ ] Alle Tests müssen mit dem Asset in der Szene bestanden sein
- [ ] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde angelegt (Zenhub Kommentar)
- [ ] Changelog des jeweiligen Release wurde aktualisiert (Wiki)
- [ ] Es gibt keine bekannten Bugs
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by splican** [comment]
Wiki Link zur Prozessbeschreibung und Knowledge Base aus dem 3D-Workflow Meeting
https://wiki.projekt-adler.eu/de/AdLerEngine/Design/3D/3D-Asset_Workflow
