### ISSUE TITLE
Unit Test Workshop durchführen

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#97]
**User Story**

Als Entwickler möchte ich die eine Überisicht über die Konventionen mit denen Unit Tests geschrieben werden erhalten, sodass alle Entwickler auf gleichen Grundlagen arbeiten.

**Akzeptanzkriterien**

- [x] Workshop vorbereitet
- [x] Workshop durchgeführt
- [x] Unit Test Richtlinien im Wiki dokumentiert

**Definition of Ready**

- [x] User Story ist klein genug für Sprint
- [x] User Story ist für jeden Beteiligten klar verständlich
- [x] User Story Aufwand ist geschätzt
- [x] User Story hat Akzeptanzkriterien
- [x] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [x] User Story Ursprung ist bekannt (Stakeholder)
- [x] User Story ist Realease zugewiesen

**Definition of Done**

- [x] Alle Akzeptanzkriterien sind erfüllt
- [x] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen
- [x] Benutzerdokumentation angelegt (Handbuch)
- [x] Technische Dokumentation angelegt (ZenHub)

**Comment by philgei** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D-3D-AdLer-Workspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/97?planning-poker) with ZenHub @AdLer-Lukas @DerKatsche @Lizardguard

**Comment by DerKatsche** [comment]
siehe https://wiki.cluuub.xyz/de/AdLerEngine/Entwicklung/Tools/Jest
