### ISSUE TITLE
Bug - Bottom Tooltip "Ausgangstür" wird permanent angezeigt

### ISSUE THREAD

**Issue by AdLer-Lukas** [ProjektAdLer/2D_3D_AdLer#978]
**User Story**

Nach dem ersten Raum wird der Bottom Tooltip für die Ausgangstür permanent angezeigt, solange kein anderer Bottom Toolltip über Mouse-Hover oder Avatar-Annäherung aufgerufen wird. 

<img width="1696" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFhLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c0b9d6b322b202d3b429935faf5c086bda4c665/image.png" alt="image.png" />

**Akzeptanzkriterien**

- [x] Bug behoben

**Definition of Ready**

- [ ] User Story ist klein genug für Sprint
- [ ] User Story ist für jeden beteiligten Entwickler klar verständlich
- [ ] User Story Aufwand ist geschätzt
- [ ] User Story hat Akzeptanzkriterien
- [ ] User Story hat einen Mehrwert für das Produkt oder die Entwicklung
- [ ] User Story Ursprung ist bekannt (Stakeholder)
- [ ] User Story ist Release zugewiesen

**Definition of Done**

- [ ] Alle Akzeptanzkriterien sind erfüllt
- [ ] Die Implementierung ist gepusht
- [ ] Die Codekonventionen sind eingehalten
- [ ] Eine Code Review wurde durchgeführt (oder in Paired Programming gearbeitet)
- [ ] Unittestabdeckung muss größer 92% sein
- [ ] Alle Tests müssen bestanden sein
- [ ] Technische Dokumentation innerhalb der Realisierung wurde, falls nötig, erstellt (Quellcode)
- [ ] Benutzerdokumentation wurde, falls nötig, angelegt (Wiki)
- [ ] Dokumentation des Vorgehens wurde, falls nötig, angelegt (Zenhub Kommentar)
- [ ] UML Aktivitätsdiagramm wurde erstellt bzw. aktualisiert falls nötig
- [ ] Changelog des jeweiligen Release wurde aktualisiert, falls erforderlich (Wiki)
- [ ] Es gibt keine bekannten Bugs
- [ ] Die Realisierung der User Story wurde erfolgreich durch den Product Owner abgenommen

**Comment by splican** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2D3DAdLerWorkspace-61b878c8596aef0010898ddd/issues/ProjektAdLer/2D_3D_AdLer/978?planning-poker) with Zenhub @DerKatsche @Grunick @Lizardguard
